---
steps:
  - checkout: self
  - task: Docker@2
    inputs:
      containerRegistry: 'gl_registry'
      command: 'login'
    displayName: Login to registry    
  - task: Docker@2
    displayName: run
    inputs:
      containerRegistry: gl_registry
      repository: sgan/containers/core/jamjon3/kube_portforward_service:latest
      command: run
      arguments: --rm --network=host -d
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  - script: |
      sleep 30
      nc -zv 192.168.1.25 3300-3310      
      nc -zv 192.168.1.25 5432-5340
      nc -zv 192.168.1.17 3300-3310
      sleep 30
      nc -z -v -w50 192.168.1.25 3306
      nc -z -v -w50 192.168.1.25 5432
      nc -z -v -w50 mysqlforward 3306
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
