---
steps:
  - checkout: self
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  - script: |
      sleep 30
      nc -zv 192.168.1.25 3300-3310      
      nc -zv 192.168.1.25 5430-5340
      nc -zv localhost 3300-3310
      sleep 30
      nc -z -v -w50 mysqlforward 3306
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
