---
steps:
  - checkout: self
  - bash: |
      /dist/constituent_tools --state $(ctstate) --action $(ctaction) --type $(cttype)
      pwd
      ls -all
      ls /data -all
    displayName: 'Run the constituent tolls app'
