parameters:
- name: state
  default: florida
  displayName: Select state for processing
  values:
  - florida
  - georgia
- name: action 
  default: import
  displayName: Tool action
  values:
  - import
- name: type
  displayName: Select the data type for import
  default: voter
  values:
  - voter
  - history
- name: export_path
  displayName: Archive Date Selection
  type: string
  default: 2020.07.07
  values:
  - 2012.04.02
  - 2012.06.02
  - 2012.07.02
  - 2012.08.06
  - 2012.09.02
  - 2012.10.03
  - 2012.12.03
  - 2013.02.28
  - 2013.03.03
  - 2013.04.03
  - 2013.06.03
  - 2013.12.06
  - 2014.01.03
  - 2014.02.07
  - 2014.03.19
  - 2014.04.07
  - 2014.05.02
  - 2014.06.06
  - 2014.08.04
  - 2014.09.04
  - 2014.10.02
  - 2014.10.22
  - 2014.12.08
  - 2015.01.07
  - 2015.02.18
  - 2015.03.23
  - 2015.04.06
  - 2015.06.23
  - 2015.07.08
  - 2015.09.17
  - 2015.10.09
  - 2015.11.09
  - 2015.12.17
  - 2016.01.14
  - 2016.02.14
  - 2016.03.07
  - 2016.04.05
  - 2016.05.03
  - 2016.06.07
  - 2016.07.12
  - 2016.08.09
  - 2016.09.08
  - 2016.10.20
  - 2016.11.01
  - 2016.12.06
  - 2017.01.10
  - 2017.02.07
  - 2017.03.07
  - 2017.05.09
  - 2017.06.14
  - 2017.07.11
  - 2017.08.08
  - 2017.09.12
  - 2017.10.10
  - 2017.11.14
  - 2017.12.12
  - 2018.01.10
  - 2018.02.13
  - 2018.03.13
  - 2018.05.10
  - 2018.06.12
  - 2018.07.10
  - 2018.08.07
  - 2018.10.15
  - 2018.11.13
  - 2018.12.11
  - 2019.01.09
  - 2019.02.12
  - 2019.03.12
  - 2019.04.03
  - 2019.05.07
  - 2019.06.04
  - 2019.07.09
  - 2019.08.13
  - 2019.09.10
  - 2019.10.08
  - 2019.11.12
  - 2019.12.10
  - 2020.01.07
  - 2020.02.11
  - 2020.03.03
  - 2020.04.07
  - 2020.06.09
  - 2020.07.07

trigger: none

pool: PodmanAgents
variables:
  - name: containerPath
    value: sgan/containers/core
  - name: ctstate
    value: ${{ parameters.state }}
  - name: ctaction
    value: ${{ parameters.action }}
  - name: cttype
    value: ${{ parameters.type }}
  - name: export_path
    value: ${{ parameters.export_path }}
  - group: DigitalOcean
  - group: usvoters_pg
resources:
  containers:
    - container: constituent_tools
      image: registry.gitlab.com/sgan/containers/core/gulfcoastgreens/constituent_tools_container:latest
      endpoint: gl_registry
      options: --add-host pgdata:$(PG_HOST) --add-host mysqlsgan:192.168.1.17
      volumes:
        - "/run/media/jam/ADULT1/VoterRegistration/Florida/$(export_path):/data"
      env:
        PG_USER: $(PG_USER)
        PG_DATABASE: $(PG_DATABASE)
        PG_HOST: $(PG_HOST)
        PG_PASSWORD: $(PG_PASSWORD)
        PG_PORT: $(PG_PORT)
stages:
  - stage: importFLVoters
    displayName: Import Florida Voters
    jobs:
      - deployment: RunConstituentToolsBatch
        displayName: Run Constituent Tools Batch
        environment: digitalocean
        pool: PodmanAgents
        container: constituent_tools
        strategy:
          runOnce:
            deploy:
              steps:
                - template: .template.yml
