parameters:
- name: export_path
  displayName: Archive Date Selection
  type: string
  default: 2020.07.07
  values:
  - 2020.07.07

trigger:
- master

pool: PodmanAgents
variables:
  - name: containerPath
    value: sgan/containers/core
  - group: DigitalOcean
  - group: usvoters_pg
resources:
  containers:
    - container: constituent_tools
      image: registry.gitlab.com/sgan/containers/core/gulfcoastgreens/constituent_tools_container:latest
      endpoint: gl_registry
      options: --add-host pgdata:$(PG_HOST) --add-host mysqlsgan:192.168.1.17
      volumes:
        - /run/media/jam/ADULT/VoterRegistration/Florida/${{ parameters.export_path }}:/data
      env:
        PG_USER: $(PG_USER)
        PG_DATABASE: $(PG_DATABASE)
        PG_HOST: $(PG_HOST)
        PG_PASSWORD: $(PG_PASSWORD)
        PG_PORT: $(PG_PORT)
stages:
  - stage: openMySQLconnection
    displayName: Open MySQL connection to SGAN cluster
    jobs:
      - job: do_sgan_myssql_fwd
        pool: PodmanAgents
        displayName: Forward Port to MySQL on SGAN-DO
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'gl_registry'
              command: 'login'
            displayName: Login to registry    
          - task: Docker@2
            displayName: run
            inputs:
              containerRegistry: gl_registry
              repository: sgan/containers/core/jamjon3/kube_portforward_service:latest
              command: run
              arguments: --rm --name sganmysql --network=host -d registry.gitlab.com/sgan/containers/core/jamjon3/kube_portforward_service:latest
  - stage: importFLVoters
    displayName: Import Florida Voters
    jobs:
      - deployment: RunConstituentToolsBatch
        displayName: Run Constituent Tools Batch
        environment: digitalocean
        pool: PodmanAgents
        container: constituent_tools
        strategy:
          runOnce:
            deploy:
              steps:
                - template: .template.yml
  - stage: closeMySQLconnection
    displayName: Close MySQL connection to SGAN cluster
    jobs:
      - job: do_sgan_myssql_fwd
        pool: PodmanAgents
        displayName: Kill Forward Port to MySQL on SGAN-DO
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'gl_registry'
              command: 'login'
            displayName: Login to registry    
          - task: Docker@2
            displayName: stop
            inputs:
              containerRegistry: gl_registry
              repository: sgan/containers/core/jamjon3/kube_portforward_service:latest
              command: stop
              arguments: sganmysql
